name: journal_analyzer
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.24.3
  - pandas
  - scikit-learn
  - tqdm
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
    - python-dotenv
    - notion-client
    - transformers
    - nltk